/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentacion;

import java.util.LinkedList;
import javax.swing.JOptionPane;
import Datos.cls_implementos;
/**
 *
 * @author poli
 */
public class frm_fincaABC extends javax.swing.JFrame {

    LinkedList<cls_implementos> implementos = new LinkedList<>();
    /**
     * Creates new form frm_fincaABC
     */
    public frm_fincaABC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        txt_tipo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_descripcion = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btn_nuevoRegistro = new javax.swing.JButton();
        btn_consultarImplemento = new javax.swing.JButton();
        btn_guardarImplemento = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(38, 222, 129));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 3, 12)); // NOI18N
        jLabel1.setText("Finca ABC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 70, 20));

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 24)); // NOI18N
        jLabel2.setText("REGISTRO DE IMPLEMENTOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 70));

        jPanel2.setBackground(new java.awt.Color(102, 255, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 550, 10));

        jPanel3.setBackground(new java.awt.Color(204, 255, 204));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel3.setText("Descripcion:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel4.setText("Codigo:");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel5.setText("Tipo:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 50, -1));

        txt_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_codigoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 200, 30));

        txt_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tipoActionPerformed(evt);
            }
        });
        jPanel3.add(txt_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 200, 30));

        txt_descripcion.setColumns(20);
        txt_descripcion.setRows(5);
        jScrollPane1.setViewportView(txt_descripcion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 200, -1));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel6.setText("Nombre:");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        jPanel3.add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 200, 30));

        jPanel4.setBackground(new java.awt.Color(38, 222, 129));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_nuevoRegistro.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btn_nuevoRegistro.setText("Nuevo ");
        btn_nuevoRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nuevoRegistroActionPerformed(evt);
            }
        });
        jPanel4.add(btn_nuevoRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 120, 30));

        btn_consultarImplemento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btn_consultarImplemento.setText("Consultar");
        btn_consultarImplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultarImplementoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_consultarImplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 120, 30));

        btn_guardarImplemento.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 12)); // NOI18N
        btn_guardarImplemento.setText("Guardar");
        btn_guardarImplemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarImplementoActionPerformed(evt);
            }
        });
        jPanel4.add(btn_guardarImplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 120, 30));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 160, 310));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 550, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_codigoActionPerformed

    private void txt_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tipoActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void nuevoRegistro(){
        txt_codigo.setText("");
        txt_descripcion.setText("");
        txt_nombre.setText("");
        txt_tipo.setText("");
    }
    private void btn_nuevoRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nuevoRegistroActionPerformed
        nuevoRegistro();
    }//GEN-LAST:event_btn_nuevoRegistroActionPerformed

    private void btn_consultarImplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultarImplementoActionPerformed
        String id = txt_codigo.getText();
        
        if(id.isEmpty()){
            JOptionPane.showMessageDialog(null, "Para consultar un implemento debes ingresar su id", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        cls_implementos implementoEncontrado = null;
        for(int i = 0; i < implementos.size(); i++){
            if(implementos.get(i).getCodigo().equals(id)){
                implementoEncontrado = implementos.get(i);
                break;
            }
        }
        
        if(implementoEncontrado != null){
            txt_nombre.setText(implementoEncontrado.getNombre());
            txt_tipo.setText(implementoEncontrado.getTipo());
            txt_descripcion.setText(implementoEncontrado.getDescripcion());
        }else{
            JOptionPane.showMessageDialog(null, "El id del implemento que ingresaste no esta registrado");
        }
    }//GEN-LAST:event_btn_consultarImplementoActionPerformed

    private boolean validarCampos(){
        String id = txt_codigo.getText();
        String nombre = txt_nombre.getText();
        String tipo = txt_tipo.getText();
        String descripcion = txt_descripcion.getText();
        
        if(id.isEmpty() || nombre.isEmpty() || tipo.isEmpty() || descripcion.isEmpty()){
            JOptionPane.showMessageDialog(null, "Para guardar un implemento debes llenar todos los campos", "Error",JOptionPane.ERROR_MESSAGE);
            return false;
        }
        
        String regexValidarTexto = "^[a-zA-ZáéíóúÁÉÍÓÚüÜñÑ\\s]+$";
        String regexValidarIdentificacion = "\\d+";
        String regxValidarDescripcion = "^[a-zA-Z0-9ñÑáéíóúÁÉÍÓÚ\\s]+$";
        
        if(!id.matches(regexValidarIdentificacion)){
            JOptionPane.showMessageDialog(null, "El id que ingreso no es valido, solo debe contener numeros");
            return false;
        }
        
        if(!nombre.matches(regexValidarTexto)){
            JOptionPane.showMessageDialog(null, "El nombre que ingreso no es valido, solo debe contener letras");
            return false;
        }
        
        if(!tipo.matches(regexValidarTexto)){
            JOptionPane.showMessageDialog(null, "El tipo de implemento que ingreso no es valido, solo debe contener letras");
            return false;
        }
        
        if(!descripcion.matches(regxValidarDescripcion)){
            JOptionPane.showMessageDialog(null, "La descripcion que ingresaste es incorrecta, solo debe contener letras y numero");
            return false;
        }
        return true;
    } 
    
    private void btn_guardarImplementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarImplementoActionPerformed
        if(validarCampos()){
            String id = txt_codigo.getText();
            String nombre = txt_nombre.getText();
            String tipo = txt_tipo.getText();
            String descripcion = txt_descripcion.getText();
            
            boolean existenciaImplemento = false;
            for(int i = 0; i < implementos.size(); i++){
                if(implementos.get(i).getCodigo().equals(id)){
                    existenciaImplemento = true;
                    break;
                }
            }
            
            if(existenciaImplemento){
                JOptionPane.showMessageDialog(null, "El id con el que intenta registrar este implemento ya esta en uso","Id en uso",JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            implementos.add(new cls_implementos(txt_codigo.getText(),txt_nombre.getText(),txt_tipo.getText(),txt_descripcion.getText()));
            JOptionPane.showMessageDialog(null, "El implemento fue registrado con exitó");
            nuevoRegistro();
        }
    }//GEN-LAST:event_btn_guardarImplementoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_fincaABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_fincaABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_fincaABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_fincaABC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_fincaABC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_consultarImplemento;
    private javax.swing.JButton btn_guardarImplemento;
    private javax.swing.JButton btn_nuevoRegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextArea txt_descripcion;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_tipo;
    // End of variables declaration//GEN-END:variables
}
